#!/bin/bash
set -x

########################################
# NOS_OFS_PREP 
########################################
export PS4=' $SECONDS + '
date
export LD_PRELOAD=/usrx/local/prod/packages/ips/18.0.1/netcdf/4.5.0/lib/libnetcdff.so.6:${LD_PRELOAD}

###################################
# Specify NET and RUN Name and model
####################################
export OFS=${OFS:-ngofs}
export NET=${NET:-nos}
export RUN=${RUN:-$OFS}

###############################################################
# Specify DBN_ALERT_TYPE_???? for different Production envir.
###############################################################
export DBN_ALERT_TYPE_NETCDF=${DBN_ALERT_TYPE_NETCDF:-NOS_OFS_FCST_NETCDF}
export DBN_ALERT_TYPE_NETCDF_LRG=${DBN_ALERT_TYPE_NETCDF_LRG:-NOS_OFS_FCST_NETCDF_LP}
export DBN_ALERT_TYPE_TEXT=${DBN_ALERT_TYPE_TEXT:-NOS_OFS_FCST_TEXT}

export cycle=t${cyc}z

########################################################
# Make working directory
########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}

if [ ! -d $DATA ]; then
  mkdir -p $DATA
  cd $DATA
else
  cd $DATA
  rm -fr $DATA/*
fi

############################################
#   Determine Job Output Name on System
############################################
export pgmout="OUTPUT.$$"
export jlogfile=${jlogfile:-${DATA}/jlogfile}

####################################
# Specify Execution Areas
####################################
export HOMEnos=${HOMEnos:-${NWROOT:?}/nosofs.${nosofs_ver:?}}
export EXECnos=${EXECnos:-${HOMEnos}/exec}
export FIXnos=${FIXnos:-${HOMEnos}/fix/shared}
export FIXofs=${FIXofs:-${HOMEnos}/fix/${OFS}}
export PARMnos=${PARMnos:-${HOMEnos}/parm}
export USHnos=${USHnos:-${HOMEnos}/ush}
export SCRIPTSnos=${SCRIPTSnos:-${HOMEnos}/scripts}

###########################################
# Run setpdy and initialize PDY variables
###########################################
#sh setpdy.sh
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMROOT=${COMROOT:-/gpfs/dell1/nco/ops/com}
export COMROOTp1=${COMROOTp1:-/gpfs/?p1/nco/ops/com}
export COMROOTp2=${COMROOTp2:-/gpfs/?p2/nco/ops/com}
export DCOMROOT=${DCOMROOT:-/gpfs/?p1/nco/ops/dcom}

export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}   # input directory
export COMOUTroot=${COMOUTroot:-${COMROOT}/${NET}/${envir}}       # output directory
export COMOUT=${COMOUT:-${COMOUTroot}/${RUN}.${PDY}}              # output directory

export COMINnestedparent=${COMINnestedparent:-${COMROOT}/${NET}/${envir}}

mkdir -m 775 -p $COMOUT

##############################################
### Set up input data path
##############################################
export COMINnam=${COMINnam:-$(compath.py nam/prod)}
export COMINhrrr=${COMINhrrr:-$(compath.py hrrr/prod)}
export COMINrap=${COMINrap:-$(compath.py rap/prod)}
export COMINgfs=${COMINgfs:-$(compath.py gfs/prod)}
export COMINrtma=${COMINrtma:-$(compath.py rtma/prod)}
export COMINetss=${COMINetss:-$(compath.py etss/prod)}
export COMINrtofs_2d=${COMINrtofs_2d:-$(compath.py rtofs/prod)}
export COMINrtofs_3d=${COMINrtofs_3d:-$(compath.py rtofs/prod)}

if [ ${RUN} == "NEGOFS" -o ${RUN} == "negofs" -o ${RUN} == "NWGOFS" -o ${RUN} == "nwgofs" ]
then
  export NESTED_PARENT_OFS=ngofs
fi

export DCOMINndfd=${DCOMROOT}/prod
export DCOMINncom=${DCOMROOT}/prod
export DCOMINusgs=${DCOMROOT}/prod
export DCOMINports=${DCOMROOT}/prod
export NOSBUFR=xx012
export USGSBUFR=xx009

##################################################################
####  Log File To Sys Report  
##################################################################
export nosjlogfile=${COMOUT}/${NET}.${RUN}.jlogfile.${PDY}.${cycle}.log 

##################################################################
####  Log File To CORMS
##################################################################
export cormslogfile=${COMOUT}/${NET}.${RUN}.corms.${PDY}.${cycle}.log

env  

########################################################
# Execute the script.
########################################################
$SCRIPTSnos/exnos_ofs_prep.sh $OFS
########################################################

cat $pgmout

postmsg "$jlogfile" "$0 completed normally"

##############################
# Remove the Temporary working directory
##############################
if [ "${KEEPDATA^^}" != YES ]; then
  rm -rf $DATA
fi

date
